name = "cf-chatbot"
main = "src/index.js"
compatibility_date = "2024-10-01"
preview_urls = true

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[ai]
binding = "AI"

